### ISSUE TITLE
bug: component creation is not working properly

### ISSUE THREAD

**Issue by theashraf** [jepser/mkcomponent#8]
## Description
creates empty files with the content of `[object Object]` only

## Expected
creates files contain javascript code with a bootstrapped React component

## Steps to Reproduce
- clone repo
- make sure you are on `master` 
- run `bin/mkcomponent` in the terminal
- check the created files

**Comment by jepser** [comment]
Hi @theashraf, which are the options you select after running `bin/mkcomponent`?

**Comment by theashraf** [comment]
I didn't select any options, I just followed the prompted questions

**Comment by jepser** [comment]
Looking into it, I will get back to you soon and sorry for the inconvenience.

**Comment by jepser** [comment]
hi @theashraf! I found the bug and it has been fixed. It affected if there is not eslint configuration added. 

Now it supports both, with or without linter. Let me know if you have any other comments :)

**Comment by theashraf** [comment]
@jepser perfect :tada:
